### ISSUE TITLE
AttributeError: 'module' object has no attribute 'nest'

### ISSUE THREAD

**Issue by VastoLorde95** [deepmind/sonnet#77]
Ubuntu 16.04. Tensorflow version 1.2.1. Doing everything in virtualenvs

I tried installing Sonnet from both pip and by compiling the source but I can't seem to get sonnet working. The build was succesful but when I try `import sonnet` it just thows me this error - AttributeError: 'module' object has no attribute 'nest'

How do I proceed?

**Comment by malcolmreynolds** [comment]
Hi @VastoLorde95 - you need to upgrade your version of TensorFlow. The current version of Sonnet only supports TF 1.5.0. I realise now there is a mistake in our README, which still says 1.2 - I'll correct that asap. In the meantime though, it's worth checking https://github.com/deepmind/sonnet/blob/master/CHANGES.md - whenever we push a release that requires a specific version of TF we mention it there, and you can see at that top that 1.16 (current version from pip) requires TF 1.5.0

We looked into making this get automatically added when you do pip install, but it's a bit tricky because there are tensorflow and tensorflow-gpu packages, and either will work.

Sorry for the confusion - let me know if you can't get it working with TF 1.5.0.

**Comment by kaisark** [comment]
Maybe install an older version of sonnet (e.g. 1.3)???

**Comment by VastoLorde95** [comment]
Upgraded Tensorflow and now it works! Closing this issue

**Comment by VastoLorde95** [comment]
I have opened a PR to fix the README
