### ISSUE TITLE
Releases? Binary builds?

### ISSUE THREAD

**Issue by hannes-brt** [deepmind/sonnet#36]
Using Sonnet is practice right now is really much harder than it should be:
Because no pre-built binaries are available and Sonnet isn't published on PyPI, every user has to go through the difficult process of installing bazel and building Sonnet themselves, as exemplified by the many issues filed by people having problems with the build process.
I have had to jump through many hoops to find a way to use Sonnet in a project which I train on Google Cloud ML Engine (the solution was to build Sonnet inside a Debian Docker container on my Mac and then to upload the resulting wheel to Google Cloud ML). This would have been much easier if binary builds were available for download.
Secondly there is no versioning yet, so it's extremely difficult to ensure different machines or environments actually run the same Sonnet version or to tell which commits break compatibility with previous versions.
I understand that Sonnet is an early piece of software, but given how widely you publicized the open-source release, could you comment on your plans to implement some versioning and packaging to make it more practical to use?

**Comment by Shuolongbj** [comment]
a good advice and the current version should be 1.0, according to compiling the generated binary installation package.

my Mac's Version
$ pip show sonnet
Name: sonnet
Version: 1.0
Summary: Sonnet is a library for building neural networks in TensorFlow.
Home-page: http://www.github.com/deepmind/sonnet/
Author: DeepMind
Author-email: sonnet-dev-os@google.com
License: Apache 2.0
Location: /Users/Ru/anaconda/envs/sonnet/lib/python2.7/site-packages
Requires: tensorflow, nose-parameterized

**Comment by malcolmreynolds** [comment]
@hannes-brt Hi, thanks for your question. I agree with all your points, we're not happy with the installation experience at the moment and obviously users have had a variety of issues with it. We've held back on offering a PyPI solution so far, principally because of developer time, but I've managed to get an engineer allocated to this full time for the next few weeks, who is going to look at packaging shortly.

My proposal is that every week, when we export from our internal version to GH, we will also bump the version number, create wheel files for Linux / Mac and python 2.7/3.4, upload them to PyPI, and update a changelog. I hope that should make use cases like yours much more straightforward - but please let me know if you think we should be doing different / additional things in order to make things user friendly.

**Comment by hannes-brt** [comment]
@malcolmreynolds That sounds great - having binaries on PyPI and regular releases should make things much easier.

**Comment by malcolmreynolds** [comment]
@hannes-brt we've added a changelog and have started bumping version numbers (currently it's 1.1). Wheel files & PyPI will follow soon.

**Comment by jramapuram** [comment]
+1 on this!

**Comment by afhuertass** [comment]
oh hi ! i'm having the same problem tryin to use Sonnet for a Google Cloud Ml , i try to upload a wheel i build in my PC ( running ubuntu 16.06 ) and use the --package option on the gcloud command to install it, but i get this error when i try to run the job:

	NotFoundError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/.local/lib/python2.7/site-packages/sonnet/python/ops/_resampler.so)

Any hints? Thanks in advance

**Comment by Shuolongbj** [comment]
@malcolmreynolds 
>>> import sonnet as snt
>>> snt.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sonnet' has no attribute '__version__'
>>> dir(snt)
['ACTCore', 'AbstractModule', 'AddBias', 'AffineGridWarper', 'AffineWarpConstraints', 'AttentiveRead', 'BatchApply', 'BatchFlatten', 'BatchNorm', 'BatchNormLSTM', 'BatchReshape', 'Conv1D', 'Conv1DLSTM', 'Conv1DTranspose', 'Conv2D', 'Conv2DLSTM', 'Conv2DTranspose', 'Conv3D', 'Conv3DTranspose', 'DeepRNN', 'DepthwiseConv2D', 'DifferentGraphError', 'Embed', 'Error', 'FlattenTrailingDimensions', 'GRU', 'GridWarper', 'InPlaneConv2D', 'IncompatibleShapeError', 'LSTM', 'LayerNorm', 'Linear', 'MergeDims', 'ModelRNN', 'Module', 'NotConnectedError', 'NotInitializedError', 'NotSupportedError', 'ParentNotBuiltError', 'RNNCore', 'Residual', 'ResidualCore', 'SAME', 'SelectInput', 'SeparableConv2D', 'Sequential', 'SkipConnectionCore', 'SliceByDim', 'TileByDim', 'TrainableInitialState', 'TrainableVariable', 'Transposable', 'UnderspecifiedError', 'VALID', 'VanillaRNN', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'absolute_import', 'check_initializers', 'check_partitioners', 'check_regularizers', 'clip_gradient', 'division', 'experimental', 'format_variable_map', 'format_variables', 'get_normalized_variable_map', 'get_saver', 'get_variables_in_module', 'get_variables_in_scope', 'has_variable_scope', 'log_variables', 'nest', 'nets', 'print_function', 'python', 'resampler', 'resampler_is_available', 'restore_initializer', 'reuse_variables', 'scale_gradient', 'variable_map_items']

**Comment by nehaljwani** [comment]
@malcolmreynolds Could you also tag the git commit with that version and/or cut a release on GH?

**Comment by malcolmreynolds** [comment]
Closing this, we have been pushing binary builds & making GH tags for a little while now.
