### ISSUE TITLE
Build failed with JDK 7

### ISSUE THREAD

**Issue by wangheda** [deepmind/sonnet#22]
I am using Ubuntu 14.04, and installed bazel with jdk1.7. The build failed with a java exception.

After I updated jdk to 1.8 version and reinstalled the corresponding bazel, the build succeeded.

Since bazel still supports jdk1.7, I wonder if you could specify the jdk requirement in installation instructions if sonnet does not.

The error is like this:

```
java.lang.NoSuchMethodError: java.util.Map.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at com.google.devtools.build.lib.actions.CompositeRunfilesSupplier.getMappings(CompositeRunfilesSupplier.java:69)
        at com.google.devtools.build.lib.sandbox.SpawnHelpers.mountRunfilesFromSuppliers(SpawnHelpers.java:146)
        at com.google.devtools.build.lib.sandbox.SpawnHelpers.getMounts(SpawnHelpers.java:55)
        at com.google.devtools.build.lib.sandbox.SandboxStrategy.getMounts(SandboxStrategy.java:153)
        at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.getMounts(LinuxSandboxedStrategy.java:42)
        at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.exec(LinuxSandboxedStrategy.java:121)
        at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.exec(LinuxSandboxedStrategy.java:90)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
        at com.google.devtools.build.lib.rules.genrule.GenRuleAction.internalExecute(GenRuleAction.java:73)
        at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:778)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:718)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:102)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:608)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:570)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:380)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:440)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:196)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:374)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:501)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```
